# Estágio de build
FROM node:20 as build

# Definir o diretório de trabalho
WORKDIR /app

# Copiar os arquivos de configuração do projeto
COPY package*.json ./

# Instalar as dependências
RUN npm install

# Copiar os arquivos do projeto
COPY . .

# Construir o aplicativo
RUN npm run build -- --configuration production

# Estágio de produção
FROM nginx:alpine

# Copiar os arquivos de build para o diretório do Nginx
COPY --from=build /app/dist/frontend /usr/share/nginx/html

# Copiar a configuração personalizada do Nginx (se necessário)
# COPY nginx.conf /etc/nginx/nginx.conf

# Expor a porta 80
EXPOSE 80

# Iniciar o Nginx
CMD ["nginx", "-g", "daemon off;"]