# Step 1: Build Stage
FROM node:18 AS build

# Define o diretório de trabalho no container
WORKDIR /app

# Copia os arquivos de dependências para o container
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante dos arquivos do projeto Angular
COPY . .

# Gera o build de produção do Angular
RUN npm run build --prod

# Step 2: Serve Stage
FROM nginx:1.23

# Remove a configuração padrão do Nginx
RUN rm -rf /usr/share/nginx/html/*

# Copia os arquivos do build do Angular para o diretório do Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Copia uma configuração customizada do Nginx, se necessário (opcional)
# COPY nginx.conf /etc/nginx/nginx.conf

# Expõe a porta usada pelo Nginx
EXPOSE 80

# Inicia o Nginx
CMD ["nginx", "-g", "daemon off;"]
