name: Build and Deploy Angular App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x' # Ajuste para a versão do Node.js que você está usando

    - name: Instalar dependências
      run: npm install

    - name: Buildar aplicação Angular
      run: npm run build -- --prod

    - name: Fazer upload dos artefatos
      uses: actions/upload-artifact@v3
      with:
        name: angular-app
        path: dist/
